const IMAGES = {
  logo: new URL("./logo.png", import.meta.url).href,
  hero: new URL("./hero.png", import.meta.url).href,
  image: new URL("./image.JPG", import.meta.url).href,
  about: new URL("./about.JPG", import.meta.url).href,
  image2: new URL("./image2.JPG", import.meta.url).href,
  image3: new URL("./image3.JPG", import.meta.url).href,
  book1: new URL("./book1.JPG", import.meta.url).href,
  book2: new URL("./book2.JPG", import.meta.url).href,
  book3: new URL("./book3.PNG", import.meta.url).href,
  lg_logo: new URL("./lg_log.png", import.meta.url).href,
  axe_logo: new URL("./axe_logo.png", import.meta.url).href,
  belaire: new URL("./belaire.png", import.meta.url).href,
  boomplay: new URL("./boomplay.png", import.meta.url).href,
  dubai: new URL("./dubai.png", import.meta.url).href,
  gulder: new URL("./gulder.png", import.meta.url).href,
  sheraton: new URL("./sheraton.jpg", import.meta.url).href,
  tecno_log: new URL("./tecno_log.webp", import.meta.url).href,
  image4: new URL("./image4.JPG", import.meta.url).href,
  image6: new URL("./image6.png", import.meta.url).href,
  image7: new URL("./image7.JPG", import.meta.url).href,
  image8: new URL("./image8.JPG", import.meta.url).href,
  image9: new URL("./image9.JPG", import.meta.url).href,
  image10: new URL("./image10.JPG", import.meta.url).href,
  image11: new URL("./image11.jpg", import.meta.url).href,
  image12: new URL("./image12.jpg", import.meta.url).href,
  image13: new URL("./image13.jpg", import.meta.url).href,
  image14: new URL("./image14.jpg", import.meta.url).href,
};

export default IMAGES;
